SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY,
SUM(PRICE*SALES) TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, SALES
    FROM BOOK B
    JOIN BOOK_SALES S 
        ON B.BOOK_ID = S.BOOK_ID
    WHERE year(SALES_DATE) = 2022
    and month(SALES_DATE) = 1
) T 
    ON A.AUTHOR_ID = T.AUTHOR_ID
GROUP BY 1, 3
ORDER BY 1,3 DESC