SELECT  D1.ID
FROM    ECOLI_DATA D1
    JOIN ECOLI_DATA D2
        ON D1.PARENT_ID = D2.ID
    JOIN ECOLI_DATA D3
        ON D2.PARENT_ID = D3.ID
WHERE NOT EXISTS(
    SELECT 1
    FROM ECOLI_DATA D4
    WHERE D3.PARENT_ID = D4.ID
)
ORDER BY 1