SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN (
    SELECT O.ANIMAL_ID, DATEDIFF(O.DATETIME, I.DATETIME) AS 보호_기간
    FROM ANIMAL_OUTS O
    JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
) D ON I.ANIMAL_ID = D.ANIMAL_ID
ORDER BY D.보호_기간 DESC
LIMIT 2;