SELECT USER_ID, NICKNAME,
concat(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) 전체주소,
concat(left(TLNO,3),'-',substr(TLNO,4,4),'-',right(TLNO,4)) 전화번호
FROM USED_GOODS_USER 
WHERE USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*)>=3
)
ORDER BY 1 DESC
