SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS I
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
    AND SEX_UPON_INTAKE like 'Intact%'
    AND (SEX_UPON_OUTCOME like 'Spayed%' OR 
         SEX_UPON_OUTCOME like 'Neutered%')
)
ORDER BY 1;
