SELECT year(SALES_DATE) YEAR,
month(SALES_DATE) MONTH,
GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM ONLINE_SALE S
JOIN USER_INFO U
    ON S.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3