SELECT DISTINCT CAR_ID,
if(CAR_ID in (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE<='2022-10-16' AND END_DATE>='2022-10-16'
),'대여중','대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
ORDER BY 1 DESC
