SELECT P.PRODUCT_ID, PRODUCT_NAME, 
SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P
    JOIN (
        SELECT  *
        FROM FOOD_ORDER
        WHERE year(PRODUCE_DATE) = 2022
        AND month(PRODUCE_DATE) = 5
    ) T     ON P.PRODUCT_ID = T.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1