SELECT H.HISTORY_ID, 
ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) 
      * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# 차 정보 테이블 JOIN
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
# 할인 정책 테이블 LEFT JOIN. 할인 정보가 없는 차도 있으므로
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE =
    CASE
        WHEN DATEDIFF(end_date,start_date)+1>=90 THEN '90일 이상'
        WHEN DATEDIFF(end_date,start_date)+1>=30 THEN '30일 이상'
        WHEN DATEDIFF(end_date,start_date)+1>=7 THEN '7일 이상'
    END
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC

