SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM  APPOINTMENT A
JOIN PATIENT P 
    ON A.PT_NO = P.PT_NO
JOIN DOCTOR D
    ON A.MDDR_ID = D.DR_ID
WHERE year(APNT_YMD) = 2022
AND month(APNT_YMD) = 4
AND day(APNT_YMD) = 13
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN != 'Y'
ORDER BY APNT_YMD
