WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 HOUR
    UNION
    SELECT HOUR+1 FROM HOUR_TABLE WHERE HOUR<23
)

SELECT  H.HOUR, ifnull(COUNT,0) COUNT
FROM    HOUR_TABLE H
LEFT JOIN    (
            SELECT hour(DATETIME) HOUR,
            COUNT(*) COUNT
            FROM ANIMAL_OUTS
            GROUP BY 1
        ) C ON(H.HOUR = C.HOUR)
ORDER BY 1
