SELECT T.ITEM_ID, P.ITEM_NAME, P.RARITY
FROM ITEM_INFO as I
    LEFT JOIN ITEM_TREE as T
        ON(I.ITEM_ID = T.PARENT_ITEM_ID)
    JOIN ITEM_INFO AS P
        ON(T.ITEM_ID = P.ITEM_ID)
WHERE I.RARITY='RARE'
ORDER BY 1 DESC;