SELECT month(START_DATE) MONTH, CAR_ID,
COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID in (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY month(START_DATE), CAR_ID
HAVING COUNT(*) !=0
ORDER BY 1, 2 DESC