SELECT YEAR(DIFFERENTIATION_DATE) 'YEAR',
(SELECT MAX(SIZE_OF_COLONY) 
 FROM ECOLI_DATA AS E2
 WHERE YEAR(E2.DIFFERENTIATION_DATE) = YEAR(E1.DIFFERENTIATION_DATE)
)-SIZE_OF_COLONY 'YEAR_DEV'
 ,ID
FROM ECOLI_DATA AS E1
ORDER BY 1, 2
