SELECT ID, FISH_NAME, LENGTH
FROM   FISH_INFO I
    JOIN
FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
WHERE ID = (
    SELECT ID
    FROM FISH_INFO I2
    WHERE I.FISH_TYPE = I2.FISH_TYPE
    ORDER BY LENGTH DESC
    LIMIT 1
)
ORDER BY ID