SELECT UB.TITLE, UR.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS, 
DATE_FORMAT(UR.CREATED_DATE,'%Y-%m-%d')
FROM USED_GOODS_REPLY AS UR
INNER JOIN USED_GOODS_BOARD AS UB
ON UR.BOARD_ID = UB.BOARD_ID
WHERE YEAR(UB.CREATED_DATE) = 2022
AND MONTH(UB.CREATED_DATE) = 10
ORDER BY UR.CREATED_DATE, UB.TITLE;