SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
if(STATUS='SALE','판매중',if(STATUS='DONE','거래완료','예약중')) 'STATUS'
FROM USED_GOODS_BOARD 
WHERE year(CREATED_DATE)=2022 
AND month(CREATED_DATE)=10
AND day(CREATED_DATE)=5
ORDER BY 1 DESC