SELECT CATEGORY, SUM(S.TOTAL_SALES) TOTAL_SALES
FROM BOOK B
    JOIN
(SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES 
WHERE year(SALES_DATE)=2022 
AND month(SALES_DATE)=1
GROUP BY BOOK_ID) S
ON (B.BOOK_ID = S.BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY;

