SELECT P1.CATEGORY, P1.PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P1
JOIN (
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) P2    ON P1.CATEGORY = P2.CATEGORY AND P1.PRICE = P2.PRICE
WHERE P1.CATEGORY in ('과자','국','김치','식용유')
ORDER BY 2 DESC